# Menu-Sidebar
menu:
  all: /
  tags: /tags

# Subtitle and Typing animation
# https://github.com/mattboldt/typed.js
subtitle:
  enable: false
  text: 

# Favicon and sidebar logo
favicon: /favicon.ico
#logo: /images/ayer-side.svg

# Cover Setting
# enable: [true|false]；path: [background-image]；logo: [cover-logo-image]
cover:
  enable: true
  path: /images/cover8.jpg # there are some beautiful cover images in Ayer's directory: /source/images, choose your favorite image to replace it.
  #logo: /images/ayer.svg

# ProgressBar
progressBar: true

# Boardcast
broadcast:
  enable: false
  #type: 2 # 1：custom，2：hitokoto api(https://hitokoto.cn/)
  #text: a clean and elegant theme, fast and responsive. # only work in custom mode

# Article Setting
# (Use this to excerpt if article is too long：<!--more-->)
article_info:
  enable: false    # This hides date, views, and word count icons
  
excerpt_all: false # Prevents the theme from pulling text automatically

# Copy code button
copy_btn: false
# Share
share_enable: true
# If you are not in China, maybe you prefer to set:false
share_china: false
# share text
share_text: Share
# search text
search_text: Search
# nav text
nav_text:
  page_prev: Prev page
  page_next: Next page
  post_prev: Newer posts
  post_next: Older posts

# Catalog in article
toc: true

# images in the article support click to fullscreen
image_viewer: true

# https://github.com/willin/hexo-wordcount
word_count:
  enable: false


# Copyright
# type：0-close all； 1-only display in article which you have configured copyright: true； 2-all articles
copyright_type: 0

# Search
# https://github.com/theme-next/hexo-generator-searchdb
search: true

# RSS
# leave it empty if you dont' need
rss:

# DarkMode
darkmode: true

# Canvas background style: 0-close，1-moveline
canvas_bg: 0

# Custom mouse pointer，replace /images/mouse.cur
mouse:
  enable: false
  path: /images/mouse.cur

# Click effect: 0-close，1-love，2-boom，3-particles
click_effect: 0

# articleWidth and sidebarWidth
layout:
  article_width: 80rem
  sidebar_width: 8rem

# GitHub Ribbons(https://github.blog/2008-12-19-github-ribbons/)
github:
  # (Set false if you don't need)
  enable: false
  url: https://github.com/Shen-Yu/hexo-theme-ayer

# pv&uv statistics
busuanzi:
  enable: false

# cnzz statistics
cnzz:
  enable: false
  url: #

# Google Analytics
google_analytics: ""
# Baidu Analytics
baidu_analytics: ""

# Mathjax Support
mathjax: true

# Katex Support
# note: need change the hexo-renderer，npm un hexo-renderer-marked -S && npm i hexo-renderer-markdown-it-katex -S
katex:
  enable: false # true
  allpost: true
  copy_tex: false

# Mermaid
mermaid:
  enable: false
  cdn: https://cdn.staticfile.org/mermaid/8.14.0/mermaid.min.js

  # Password Lock
lock:
  enable: false
  password: 
  
# Music Player
music:
  enable: false
  type: 1 # 1: CloudMusic, 2: Meting
  id: 
  server: netease
